import { getLLMClient, CLAUDE_MODELS } from './llm/client'
import { RAGSystem } from './rag';
import { logger } from './utils/logger'
import { COMPLIANCE_AGENT_PROMPT } from './prompts/agent-prompts'

interface ComplianceCheckResult {
  category: string;
  status: 'compliant' | 'suggestion' | 'warning' | 'critical';
  message: string;
  recommendations?: string[];
}

export class ComplianceCheckerAgent {
  private llm = getLLMClient();
  private ragSystem: RAGSystem;

  constructor() {
    this.llm = getLLMClient();
    this.ragSystem = new RAGSystem();
  }

  async checkCompliance(
    saasDescription: string,
    generatedTheme: any,
    generatedBlueprint: any,
    generatedLandingPage: any,
    generatedGrowthPlan: any
  ): Promise<ComplianceCheckResult[]> {
    const complianceContext = await this.ragSystem.search(
      "SaaS Product-Market Fit & Strategy Best Practices, SaaS Engineering Excellence Best Practices, SaaS Security & Compliance Best Practices, Apple Design Principles",
      5
    );
    const contextContent = complianceContext.map(doc => doc.content).join('\n\n');

    const prompt = `Review the following SaaS application details against best practices in product strategy, engineering, security, and design. Provide a list of compliance checks, suggestions, warnings, or critical issues. Focus on actionable feedback.

SaaS Description: ${saasDescription}

Generated Theme: ${JSON.stringify(generatedTheme, null, 2)}
Generated Blueprint: ${JSON.stringify(generatedBlueprint, null, 2)}
Generated Landing Page: ${JSON.stringify(generatedLandingPage, null, 2)}
Generated Growth Plan: ${JSON.stringify(generatedGrowthPlan, null, 2)}

Best Practices Context:\n${contextContent}

Provide the output as a JSON array of objects with the following structure:
[
  {
    "category": "string" (e.g., "Security", "Design", "Performance", "Strategy"),
    "status": "compliant" | "suggestion" | "warning" | "critical",
    "message": "string",
    "recommendations": ["string"] (optional)
  }
]
`;

    const response = await this.llm.chat({
      model: CLAUDE_MODELS.HAIKU,
      messages: [
        { role: "system", content: COMPLIANCE_AGENT_PROMPT },
        { role: "user", content: prompt },
      ],
      temperature: 0.5,
      max_tokens: 2000,
      response_format: { type: "json_object" },
    });

    const resultJson = response.content;
    if (!resultJson) {
      throw new Error("Failed to generate compliance check results.");
    }

    try {
      const results: ComplianceCheckResult[] = JSON.parse(resultJson);
      return results;
    } catch (e) {
      logger.error("Failed to parse compliance check results JSON:", resultJson, e);
      throw new Error("Invalid compliance check results format generated by AI.");
    }
  }
}
