import OpenAI from 'openai';
import { RAGSystem } from './rag';

interface GrowthPlan {
  seo: {
    metaTitle: string;
    metaDescription: string;
    keywords: string[];
  };
  socialMediaPosts: Array<{
    platform: string;
    content: string;
    hashtags: string[];
  }>;
  emailCampaign: Array<{
    subject: string;
    body: string;
  }>;
}

export class GrowthHackerAgent {
  private openai: OpenAI;
  private ragSystem: RAGSystem;

  constructor() {
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
    this.ragSystem = new RAGSystem();
  }

  async generateGrowthPlan(saasDescription: string): Promise<GrowthPlan> {
    // Retrieve relevant growth and retention principles from the knowledge base
    const growthPrinciples = await this.ragSystem.search(
      "SaaS Growth & Retention Best Practices",
      2
    );
    const growthContext = growthPrinciples
      .map((doc) => doc.content)
      .join("\n\n");

    const prompt = `Generate a comprehensive growth plan for a SaaS application based on the following description. The plan should include SEO strategy, social media posts, and an email campaign. Adhere to the provided growth and retention best practices to ensure sustainable success.

Description: ${saasDescription}

Growth & Retention Context:\n${growthContext}\n
Provide the output as a JSON object with the following structure:
{
  "seo": {
    "metaTitle": "string",
    "metaDescription": "string",
    "keywords": ["string"]
  },
  "socialMediaPosts": [
    {
      "platform": "string" (e.g., "LinkedIn", "Twitter"),
      "content": "string",
      "hashtags": ["string"]
    }
  ],
  "emailCampaign": [
    {
      "subject": "string",
      "body": "string"
    }
  ]
}

Ensure the content is engaging, relevant, and optimized for growth.`;

    const response = await this.openai.chat.completions.create({
      model: "gpt-4o-mini", // Use a suitable model
      messages: [
        { role: "system", content: "You are an AI Growth Hacker that generates effective marketing strategies for SaaS products." },
        { role: "user", content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 1500,
      response_format: { type: "json_object" },
    });

    const planJson = response.choices[0].message.content;
    if (!planJson) {
      throw new Error("Failed to generate growth plan.");
    }

    try {
      const plan: GrowthPlan = JSON.parse(planJson);
      return plan;
    } catch (e) {
      console.error("Failed to parse generated growth plan JSON:", planJson, e);
      throw new Error("Invalid growth plan format generated by AI.");
    }
  }
}
