import OpenAI from 'openai';
import { RAGSystem } from './rag';
import { WarRoomOrchestrator, AgentMessage, AgentContext } from './war-room-orchestrator';

interface GrowthPlan {
  seo: {
    metaTitle: string;
    metaDescription: string;
    keywords: string[];
  };
  socialMediaPosts: Array<{
    platform: string;
    content: string;
    hashtags: string[];
  }>;
  emailCampaign: Array<{
    subject: string;
    body: string;
  }>;
}

export class GrowthHackerAgent {
  private openai: OpenAI;
  private ragSystem: RAGSystem;
  private orchestrator?: WarRoomOrchestrator;

  constructor(orchestrator?: WarRoomOrchestrator) {
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
    this.ragSystem = new RAGSystem();
    this.orchestrator = orchestrator;
  }

  async generateGrowthPlan(saasDescription: string, currentContext?: AgentContext): Promise<GrowthPlan> {
    if (this.orchestrator) {
      await this.orchestrator.sendMessage({
        sender: 'AI Growth Hacker Agent',
        recipient: 'Orchestrator',
        type: 'info',
        content: `Starting growth plan generation for: ${saasDescription}`,
      });
    }

    let refinedDescription = saasDescription;
    if (currentContext?.saasDescription) {
      refinedDescription = currentContext.saasDescription;
    }

    // Retrieve relevant growth and retention principles from the knowledge base
    const growthPrinciples = await this.ragSystem.search(
      "SaaS Growth & Retention Best Practices",
      2
    );
    const growthContext = growthPrinciples
      .map((doc) => doc.content)
      .join("\n\n");

    const prompt = `Generate a comprehensive growth plan for a SaaS application based on the following description. The plan should include SEO strategy, social media posts, and an email campaign. Adhere to the provided growth and retention best practices to ensure sustainable success.

Description: ${refinedDescription}

Growth & Retention Context:\n${growthContext}\n
Provide the output as a JSON object with the following structure:
{
  "seo": {
    "metaTitle": "string",
    "metaDescription": "string",
    "keywords": ["string"]
  },
  "socialMediaPosts": [
    {
      "platform": "string" (e.g., "LinkedIn", "Twitter"),
      "content": "string",
      "hashtags": ["string"]
    }
  ],
  "emailCampaign": [
    {
      "subject": "string",
      "body": "string"
    }
  ]
}

Ensure the content is engaging, relevant, and optimized for growth.`;

    const response = await this.openai.chat.completions.create({
      model: "gpt-4o-mini", // Use a suitable model
      messages: [
        { role: "system", content: "You are an AI Growth Hacker that generates effective marketing strategies for SaaS products." },
        { role: "user", content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 1500,
      response_format: { type: "json_object" },
    });

    const planJson = response.choices[0].message.content;
    if (!planJson) {
      if (this.orchestrator) {
        await this.orchestrator.sendMessage({
          sender: 'AI Growth Hacker Agent',
          recipient: 'Orchestrator',
          type: 'critical',
          content: 'Failed to generate growth plan content.',
        });
      }
      throw new Error("Failed to generate growth plan.");
    }

    try {
      const plan: GrowthPlan = JSON.parse(planJson);
      if (this.orchestrator) {
        await this.orchestrator.sendMessage({
          sender: 'AI Growth Hacker Agent',
          recipient: 'Orchestrator',
          type: 'response',
          content: 'Growth plan generated successfully.',
          payload: plan,
        });
        this.orchestrator.updateContext({ growthPlan: plan });
      }
      return plan;
    } catch (e) {
      console.error("Failed to parse generated growth plan JSON:", planJson, e);
      if (this.orchestrator) {
        await this.orchestrator.sendMessage({
          sender: 'AI Growth Hacker Agent',
          recipient: 'Orchestrator',
          type: 'critical',
          content: `Invalid growth plan format generated by AI: ${planJson}`,
        });
      }
      throw new Error("Invalid growth plan format generated by AI.");
    }
  }
}
