import OpenAI from 'openai';
import { RAGSystem } from './rag';
import { WarRoomOrchestrator, AgentMessage, AgentContext } from './war-room-orchestrator';
import { logger } from './utils/logger'
import { LANDING_PAGE_PROMPT } from './prompts/agent-prompts'

interface LandingPageContent {
  hero: {
    headline: string;
    subheadline: string;
    callToAction: string;
  };
  features: Array<{
    title: string;
    description: string;
  }>;
  pricing: Array<{
    planName: string;
    price: string;
    features: string[];
    callToAction: string;
  }>;
  testimonials: Array<{
    quote: string;
    author: string;
    company: string;
  }>;
  // Add more sections as needed (e.g., FAQ, About Us)
}

export class LandingPageGenerator {
  private openai: OpenAI;
  private ragSystem: RAGSystem;
  private orchestrator?: WarRoomOrchestrator;

  constructor(orchestrator?: WarRoomOrchestrator) {
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
    this.ragSystem = new RAGSystem();
    this.orchestrator = orchestrator;
  }

  async generateContent(saasDescription: string, currentContext?: AgentContext): Promise<LandingPageContent> {
    if (this.orchestrator) {
      await this.orchestrator.sendMessage({
        sender: 'Landing Page Generator',
        recipient: 'Orchestrator',
        type: 'info',
        content: `Starting landing page content generation for: ${saasDescription}`,
      });
    }

    let refinedDescription = saasDescription;
    if (currentContext?.saasDescription) {
      refinedDescription = currentContext.saasDescription;
    }

    // Retrieve relevant product-market fit and strategy principles from the knowledge base
    const strategyPrinciples = await this.ragSystem.search(
      "SaaS Product-Market Fit & Strategy Best Practices",
      2
    );
    const strategyContext = strategyPrinciples
      .map((doc) => doc.content)
      .join("\n\n");

    const prompt = `Generate compelling and structured content for a landing page for a SaaS application based on the following description. Adhere to the provided product-market fit and strategy best practices to ensure high conversion and value proposition.

Description: ${refinedDescription}

Product-Market Fit & Strategy Context:\n${strategyContext}\n
Include the following sections:
1.  **Hero Section**: A catchy headline, a concise subheadline, and a strong call to action.
2.  **Features Section**: 3-4 key features, each with a title and a brief description.
3.  **Pricing Section**: 2-3 pricing plans (e.g., Basic, Pro, Enterprise), each with a plan name, price (e.g., "$X/month"), 3-4 bullet-point features, and a call to action.
4.  **Testimonials Section**: 2-3 short, positive testimonials with author names and company names.

Provide the output as a JSON object with the following structure:
{
  "hero": {
    "headline": "string",
    "subheadline": "string",
    "callToAction": "string"
  },
  "features": [
    {
      "title": "string",
      "description": "string"
    }
  ],
  "pricing": [
    {
      "planName": "string",
      "price": "string",
      "features": ["string"],
      "callToAction": "string"
    }
  ],
  "testimonials": [
    {
      "quote": "string",
      "author": "string",
      "company": "string"
    }
  ]
}

Ensure the content is engaging, benefit-oriented, and suitable for a SaaS landing page.`;

    const response = await this.openai.chat.completions.create({
      model: "gpt-4o-mini", // Use a suitable model
      messages: [
        { role: "system", content: LANDING_PAGE_PROMPT },
        { role: "user", content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 1500,
      response_format: { type: "json_object" },
    });

    const contentJson = response.choices[0].message.content;
    if (!contentJson) {
      if (this.orchestrator) {
        await this.orchestrator.sendMessage({
          sender: 'Landing Page Generator',
          recipient: 'Orchestrator',
          type: 'critical',
          content: 'Failed to generate landing page content.',
        });
      }
      throw new Error("Failed to generate landing page content.");
    }

    try {
      const content: LandingPageContent = JSON.parse(contentJson);
      if (this.orchestrator) {
        await this.orchestrator.sendMessage({
          sender: 'Landing Page Generator',
          recipient: 'Orchestrator',
          type: 'response',
          content: 'Landing page content generated successfully.',
          payload: content,
        });
        this.orchestrator.updateContext({ landingPage: content });
      }
      return content;
    } catch (e) {
      logger.error("Failed to parse generated landing page content JSON:", contentJson, e);
      if (this.orchestrator) {
        await this.orchestrator.sendMessage({
          sender: 'Landing Page Generator',
          recipient: 'Orchestrator',
          type: 'critical',
          content: `Invalid landing page content format generated by AI: ${contentJson}`,
        });
      }
      throw new Error("Invalid landing page content format generated by AI.");
    }
  }
}
