import OpenAI from 'openai';

interface GeneratedTheme {
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  fontFamily: string;
  borderRadius: string;
  // Add more theme properties as needed
}

export class ThemeGenerator {
  private openai: OpenAI;

  constructor() {
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }

  async generateTheme(saasDescription: string): Promise<GeneratedTheme> {
    const prompt = `Generate a modern UI theme (primary, secondary, accent colors in hex, font family, border radius in rem) for a SaaS application based on the following description:

Description: ${saasDescription}

Provide the output as a JSON object with the following structure:
{
  "primaryColor": "#HEXCODE",
  "secondaryColor": "#HEXCODE",
  "accentColor": "#HEXCODE",
  "fontFamily": "Font Name",
  "borderRadius": "Xrem"
}

Ensure the colors are harmonious and suitable for the SaaS type.`;

    const response = await this.openai.chat.completions.create({
      model: "gpt-4o-mini", // Use a suitable model
      messages: [
        { role: "system", content: "You are a UI/UX designer AI that generates modern and harmonious themes for SaaS applications." },
        { role: "user", content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 200,
      response_format: { type: "json_object" },
    });

    const themeJson = response.choices[0].message.content;
    if (!themeJson) {
      throw new Error("Failed to generate theme.");
    }

    try {
      const theme: GeneratedTheme = JSON.parse(themeJson);
      return theme;
    } catch (e) {
      console.error("Failed to parse generated theme JSON:", themeJson, e);
      throw new Error("Invalid theme format generated by AI.");
    }
  }
}
