/**
 * @saas-factory/shared-types/saas
 *
 * Types used inside generated SaaS applications.
 * Every SaaS app generated by the factory imports from this package
 * to ensure type compatibility with the factory-brain agents.
 */

// ── Core SaaS Entities ────────────────────────────────────────────────────────

export interface SaaSUser {
  id: string
  saasId: string
  email: string
  displayName: string | null
  avatarUrl: string | null
  role: UserRole
  plan: string
  metadata: Record<string, unknown>
  createdAt: string
  updatedAt: string
}

export type UserRole = 'owner' | 'admin' | 'member' | 'viewer' | 'user'

export interface SaaSOrganization {
  id: string
  saasId: string
  name: string
  slug: string
  ownerId: string
  plan: string
  metadata: Record<string, unknown>
  createdAt: string
  updatedAt: string
}

export interface SaaSSubscription {
  id: string
  saasId: string
  userId: string
  stripeSubscriptionId: string | null
  stripeCustomerId: string | null
  plan: string
  status: SubscriptionStatus
  currentPeriodStart: string | null
  currentPeriodEnd: string | null
  trialEnd: string | null
  cancelAt: string | null
  metadata: Record<string, unknown>
  createdAt: string
  updatedAt: string
}

export type SubscriptionStatus =
  | 'active'
  | 'trialing'
  | 'past_due'
  | 'canceled'
  | 'paused'
  | 'incomplete'
  | 'incomplete_expired'

// ── Auth Types ────────────────────────────────────────────────────────────────

export interface AuthSession {
  userId: string
  email: string
  role: UserRole
  plan: string
  saasId: string
  orgId?: string
  expiresAt: number
}

export interface AuthTokens {
  accessToken: string
  refreshToken: string
  expiresIn: number
}

export interface LoginRequest {
  email: string
  password: string
}

export interface SignupRequest {
  email: string
  password: string
  displayName?: string
  inviteToken?: string
}

// ── API Response Wrappers ─────────────────────────────────────────────────────

export interface ApiResponse<T = unknown> {
  data: T
  meta?: {
    page?: number
    pageSize?: number
    total?: number
    hasMore?: boolean
  }
}

export interface ApiError {
  error: string
  code?: string
  details?: Record<string, string[]>
  statusCode: number
}

export type ApiResult<T> = ApiResponse<T> | ApiError

// ── Pagination ────────────────────────────────────────────────────────────────

export interface PaginationParams {
  page?: number
  pageSize?: number
  cursor?: string
}

export interface PaginatedResult<T> {
  items: T[]
  total: number
  page: number
  pageSize: number
  hasMore: boolean
  nextCursor?: string
}

// ── Feature Flags (runtime) ───────────────────────────────────────────────────

export interface FeatureFlag {
  key: string
  enabled: boolean
  rolloutPct: number
  metadata: Record<string, unknown>
}

export interface FeatureFlagContext {
  userId: string
  saasId: string
  plan: string
  role: UserRole
}

// ── Analytics Events ──────────────────────────────────────────────────────────

export interface AnalyticsEvent {
  event: string
  userId?: string
  saasId: string
  properties?: Record<string, unknown>
  timestamp?: string
}

// ── Webhook Payloads ──────────────────────────────────────────────────────────

export interface WebhookPayload<T = unknown> {
  id: string
  type: string
  saasId: string
  data: T
  createdAt: string
  signature: string
}

// ── Stripe Webhook Events ─────────────────────────────────────────────────────

export interface StripeWebhookEvent {
  id: string
  type: StripeEventType
  data: {
    object: Record<string, unknown>
  }
  created: number
}

export type StripeEventType =
  | 'customer.subscription.created'
  | 'customer.subscription.updated'
  | 'customer.subscription.deleted'
  | 'customer.subscription.trial_will_end'
  | 'invoice.payment_succeeded'
  | 'invoice.payment_failed'
  | 'checkout.session.completed'
  | 'customer.created'
  | 'customer.deleted'

// ── Email Templates ───────────────────────────────────────────────────────────

export interface EmailTemplate {
  to: string | string[]
  subject: string
  from?: string
  replyTo?: string
  template: EmailTemplateName
  variables: Record<string, string | number | boolean>
}

export type EmailTemplateName =
  | 'welcome'
  | 'email-verification'
  | 'password-reset'
  | 'invitation'
  | 'subscription-started'
  | 'subscription-canceled'
  | 'payment-failed'
  | 'trial-ending'
  | 'custom'

// ── File Upload ───────────────────────────────────────────────────────────────

export interface UploadedFile {
  id: string
  saasId: string
  userId: string
  bucket: string
  key: string
  filename: string
  mimeType: string
  sizeBytes: number
  url: string
  metadata: Record<string, unknown>
  createdAt: string
}

export interface PresignedUploadUrl {
  uploadUrl: string
  fileKey: string
  expiresAt: string
  maxSizeBytes: number
}

// ── Plan Limits ───────────────────────────────────────────────────────────────

export interface PlanLimits {
  users: number | 'unlimited'
  storage: number | 'unlimited'  // in MB
  apiRequests: number | 'unlimited'  // per month
  customDomains: number | 'unlimited'
  teamMembers: number | 'unlimited'
  [key: string]: number | 'unlimited'
}

export interface PlanConfig {
  id: string
  name: string
  slug: string
  price: number
  currency: string
  interval: 'month' | 'year'
  limits: PlanLimits
  features: string[]
  stripePriceId?: string
}

// ── Notification ──────────────────────────────────────────────────────────────

export interface Notification {
  id: string
  userId: string
  saasId: string
  type: NotificationType
  title: string
  message: string
  read: boolean
  actionUrl?: string
  metadata: Record<string, unknown>
  createdAt: string
}

export type NotificationType =
  | 'info'
  | 'success'
  | 'warning'
  | 'error'
  | 'payment'
  | 'team'
  | 'system'
