# Redis Sentinel 3 Configuration

port 26379
bind 0.0.0.0

# Sentinel working directory
dir /data

# Log file
logfile ""
loglevel notice

# Master name and quorum
sentinel monitor mymaster redis-master 6379 2

# Master failover timeout
sentinel down-after-milliseconds mymaster 30000
sentinel parallel-syncs mymaster 1
sentinel failover-timeout mymaster 180000

# TCP keepalive
sentinel tcp-keepalive 300

# Deny traffic from non-Sentinel processes
protected-mode yes
