apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saas-factory

resources:
  - namespace-and-ingress.yaml
  - factory-dashboard.yaml
  - factory-brain.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: saas-factory
